name: 'Process Vulnerabilities'
description: 'Processes scan results and generates vulnerability reports'
author: 'Your Organization'

inputs:
  scan-results-path:
    description: 'Path to the scan results JSON file'
    required: true
    default: 'full-scan-results.json'
  repository:
    description: 'Repository name (owner/repo format)'
    required: true

outputs:
  vulnerability-count:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.extract.outputs.fixable_count }}
  has-vulnerabilities:
    description: 'Whether vulnerabilities were found'
    value: ${{ steps.extract.outputs.fixable_count > 0 }}
  detailed-results-path:
    description: 'Path to detailed vulnerabilities JSON'
    value: 'detailed-vulnerabilities.json'
  report-path:
    description: 'Path to vulnerability report markdown'
    value: 'vulnerability-context.md'

runs:
  using: "composite"
  steps:
    - name: Extract high-risk vulnerabilities and generate summary
      shell: bash
      run: |
        echo "INFO: Starting vulnerability data extraction and processing"
        
        # Check if scan results exist and are valid
        if [ ! -f "${{ inputs.scan-results-path }}" ] || [ ! -s "${{ inputs.scan-results-path }}" ]; then
          echo "WARNING: No scan results found, creating empty vulnerability dataset"
          echo '{"vulnerabilities": []}' > ${{ inputs.scan-results-path }}
        fi
        
        # Extract all vulnerabilities for display
        echo "INFO: Extracting all vulnerabilities"
        jq '.vulnerabilities[] | {title: .title, severity: .severity, package: .packageName, version: .version, identifiers: .identifiers}' ${{ inputs.scan-results-path }} || echo "No vulnerabilities found"
        
        # Generate vulnerability summary
        echo "## Snyk Vulnerability Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Scan Date:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        HIGH_COUNT=$(jq '[.vulnerabilities[] | select(.severity == "high")] | length' ${{ inputs.scan-results-path }} 2>/dev/null || echo "0")
        CRITICAL_COUNT=$(jq '[.vulnerabilities[] | select(.severity == "critical")] | length' ${{ inputs.scan-results-path }} 2>/dev/null || echo "0")
        MEDIUM_COUNT=$(jq '[.vulnerabilities[] | select(.severity == "medium")] | length' ${{ inputs.scan-results-path }} 2>/dev/null || echo "0")
        LOW_COUNT=$(jq '[.vulnerabilities[] | select(.severity == "low")] | length' ${{ inputs.scan-results-path }} 2>/dev/null || echo "0")
        TOTAL_COUNT=$(jq '[.vulnerabilities[]] | length' ${{ inputs.scan-results-path }} 2>/dev/null || echo "0")
        
        echo "**Total Vulnerabilities:** $TOTAL_COUNT" >> $GITHUB_STEP_SUMMARY
        echo "**Critical Vulnerabilities:** $CRITICAL_COUNT" >> $GITHUB_STEP_SUMMARY
        echo "**High Vulnerabilities:** $HIGH_COUNT" >> $GITHUB_STEP_SUMMARY
        echo "**Medium Vulnerabilities:** $MEDIUM_COUNT" >> $GITHUB_STEP_SUMMARY
        echo "**Low Vulnerabilities:** $LOW_COUNT" >> $GITHUB_STEP_SUMMARY
        
        # Create filtered results for all vulnerabilities (not just high-severity)
        jq '.vulnerabilities[]' ${{ inputs.scan-results-path }} > snyk-results.json || echo "[]" > snyk-results.json

    - name: Extract fixable vulnerabilities
      id: extract
      shell: bash
      run: |
        echo "INFO: Processing vulnerability data for fixable issues"
        
        echo "INFO: Filtering all severity vulnerabilities"
        jq -c '.vulnerabilities[]? // [] | {
          id: (.id // "unknown"),
          title: (.title // "Unknown Vulnerability"),
          severity: (.severity // "unknown"),
          packageName: (.packageName // "unknown"),
          version: (.version // "unknown"),
          nearestFixedInVersion: (.nearestFixedInVersion // null),
          isUpgradable: (.isUpgradable // false),
          isPatchable: (.isPatchable // false),
          upgradePath: (.upgradePath // []),
          description: (.description // "No description available"),
          references: (.references // []),
          CVSSv3: (.CVSSv3 // null),
          from: (.from // [])
        }' ${{ inputs.scan-results-path }} 2>/dev/null | jq -s '.' > detailed-vulnerabilities.json || echo "[]" > detailed-vulnerabilities.json
        
        VULN_COUNT=$(jq 'length' detailed-vulnerabilities.json 2>/dev/null | head -n 1 | tr -d '\n\r' || echo "0")
        
        if ! [[ "$VULN_COUNT" =~ ^[0-9]+$ ]]; then
          echo "WARNING: Invalid vulnerability count detected, setting to 0"
          VULN_COUNT=0
        fi
        echo "fixable_count=$VULN_COUNT" >> $GITHUB_OUTPUT
        echo "INFO: Identified $VULN_COUNT vulnerabilities requiring attention"
        
        echo "INFO: Generating comprehensive vulnerability analysis report"
        echo "# Security Vulnerability Analysis Report" > vulnerability-context.md
        echo "" >> vulnerability-context.md
        echo "**Project:** ${{ inputs.repository }}" >> vulnerability-context.md
        echo "**Scan Date:** $(date)" >> vulnerability-context.md
        echo "**Total Vulnerabilities:** $VULN_COUNT" >> vulnerability-context.md
        echo "" >> vulnerability-context.md
        
        echo "## Detected Vulnerabilities" >> vulnerability-context.md
        echo "" >> vulnerability-context.md
        
        if [ "$VULN_COUNT" -gt 0 ] 2>/dev/null; then
          echo "INFO: Processing detailed vulnerability information for $VULN_COUNT vulnerabilities"
          jq -r '.[] | "### \(.title // "Unknown Vulnerability") (\(.severity // "unknown" | ascii_upcase))
          
          **Package:** \(.packageName // "unknown")@\(.version // "unknown")
          **CVE ID:** \(.id // "N/A")
          **CVSS Score:** \(.CVSSv3 // "N/A")
          **Current Version:** \(.version // "unknown")
          **Fixed In:** \(.nearestFixedInVersion // "No direct fix available")
          **Upgradable:** \(.isUpgradable // false)
          **Patchable:** \(.isPatchable // false)
          **Dependency Path:** \(if .from then (.from | if type == "array" then join(" → ") else tostring end) else "Direct dependency" end)
          
          **Description:** \(.description // "No description available")
          
          **References:**
          \(if .references then 
            (if (.references | type) == "array" then 
              (.references | map("- \(.)") | join("\n")) 
            else 
              "- \(.references)" 
            end) 
          else 
            "No references available" 
          end)
          
          ---
          "' detailed-vulnerabilities.json >> vulnerability-context.md 2>/dev/null || echo "ERROR: Failed to process vulnerability details" >> vulnerability-context.md
        else
          echo "INFO: No vulnerabilities detected in this scan"
          echo "No vulnerabilities detected." >> vulnerability-context.md
          echo "" >> vulnerability-context.md
          echo "STATUS: This project appears to be secure from high and critical vulnerabilities." >> vulnerability-context.md
        fi
        echo "SUCCESS: Vulnerability analysis and report generation completed"

branding:
  icon: 'file-text'
  color: 'orange'
